-- MySQL Script generated by MySQL Workbench
-- Mon May 13 19:34:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema conjuntos_residenciales
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `conjuntos_residenciales` ;

-- -----------------------------------------------------
-- Schema conjuntos_residenciales
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `conjuntos_residenciales` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `conjuntos_residenciales` ;

-- -----------------------------------------------------
-- Table `conjuntos_residenciales`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conjuntos_residenciales`.`table1` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `conjuntos_residenciales`.`table1` (
)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `conjuntos_residenciales`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conjuntos_residenciales`.`roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `conjuntos_residenciales`.`roles` (
  `cod_rol` INT NOT NULL AUTO_INCREMENT,
  `Rolname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_rol`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `conjuntos_residenciales`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conjuntos_residenciales`.`Usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `conjuntos_residenciales`.`Usuario` (
  `identificacion` INT NOT NULL,
  `cod_rol` VARCHAR(45) NOT NULL,
  `user_nombres` VARCHAR(45) NOT NULL,
  `user_apellidos` VARCHAR(45) NOT NULL,
  `user_telefono` VARCHAR(45) NOT NULL,
  `user_correo` VARCHAR(45) NOT NULL,
  `user_fnacimiento` DATE NOT NULL,
  PRIMARY KEY (`identificacion`),
  CONSTRAINT `cod_rol`
    FOREIGN KEY (`identificacion`)
    REFERENCES `conjuntos_residenciales`.`roles` (`cod_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `conjuntos_residenciales`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conjuntos_residenciales`.`evento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `conjuntos_residenciales`.`evento` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `evento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_evento`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `conjuntos_residenciales`.`Reserva_evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conjuntos_residenciales`.`Reserva_evento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `conjuntos_residenciales`.`Reserva_evento` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `identificacion` VARCHAR(45) NOT NULL,
  `fechaEvento` VARCHAR(45) NOT NULL,
  `id_evento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_reserva`),
  CONSTRAINT `id_evento`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `conjuntos_residenciales`.`evento` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `identificacion`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `conjuntos_residenciales`.`Usuario` (`identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `conjuntos_residenciales`.`reserva_parqueadero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conjuntos_residenciales`.`reserva_parqueadero` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `conjuntos_residenciales`.`reserva_parqueadero` (
  `id_Parqueadero` INT NOT NULL AUTO_INCREMENT,
  `Num_Parqueadero` VARCHAR(45) NOT NULL,
  `identificacion` VARCHAR(45) NOT NULL,
  `Fecha_Reservado` DATE NOT NULL,
  PRIMARY KEY (`id_Parqueadero`),
  CONSTRAINT `identificacion`
    FOREIGN KEY (`id_Parqueadero`)
    REFERENCES `conjuntos_residenciales`.`Usuario` (`identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `conjuntos_residenciales`.`Usuario_Casa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conjuntos_residenciales`.`Usuario_Casa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `conjuntos_residenciales`.`Usuario_Casa` (
  `id_casa` INT NOT NULL AUTO_INCREMENT,
  `Casa` VARCHAR(45) NOT NULL,
  `identificaion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_casa`),
  CONSTRAINT `identificacion`
    FOREIGN KEY (`id_casa`)
    REFERENCES `conjuntos_residenciales`.`Usuario` (`identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
