-- MySQL Script generated by MySQL Workbench
-- Wed Aug 28 19:58:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema conjuntos_reservas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema conjuntos_reservas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `conjuntos_reservas` DEFAULT CHARACTER SET utf8 ;
USE `conjuntos_reservas` ;

-- -----------------------------------------------------
-- Table `conjuntos_reservas`.`ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conjuntos_reservas`.`ROLES` (
  `cod_rol` INT NOT NULL AUTO_INCREMENT,
  `rol_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cod_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conjuntos_reservas`.`HOUSE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conjuntos_reservas`.`HOUSE` (
  `cod_house` INT NOT NULL AUTO_INCREMENT,
  `house_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_house`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conjuntos_reservas`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conjuntos_reservas`.`USERS` (
  `cod_rol` INT NOT NULL,
  `cod_user` INT NOT NULL AUTO_INCREMENT,
  `cod_house` INT NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `user_lastname` VARCHAR(45) NOT NULL,
  `user_birthday` DATE NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  `user_pass` VARCHAR(45) NOT NULL,
  `user_phone` VARCHAR(80) NOT NULL,
  `user_state` TINYINT NOT NULL,
  PRIMARY KEY (`cod_user`),
  INDEX `FK_cod_house_idx` (`cod_house` ASC) VISIBLE,
  CONSTRAINT `FK_user_rol`
    FOREIGN KEY (`cod_rol`)
    REFERENCES `conjuntos_reservas`.`ROLES` (`cod_rol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_cod_house`
    FOREIGN KEY (`cod_house`)
    REFERENCES `conjuntos_reservas`.`HOUSE` (`cod_house`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conjuntos_reservas`.`PLACES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conjuntos_reservas`.`PLACES` (
  `cod_place` INT NOT NULL AUTO_INCREMENT,
  `place_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_place`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conjuntos_reservas`.`BOOKING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conjuntos_reservas`.`BOOKING` (
  `booking_date` DATE NOT NULL,
  `cod_booking` INT NOT NULL AUTO_INCREMENT,
  `cod_user` INT NOT NULL,
  `cod_place` INT NOT NULL,
  `booking_status` ENUM('approved', 'pending', 'rejected') NOT NULL DEFAULT 'pending',
  PRIMARY KEY (`cod_booking`),
  INDEX `cod_user_idx` (`cod_user` ASC) VISIBLE,
  INDEX `cod_place_idx` (`cod_place` ASC) VISIBLE,
  CONSTRAINT `cod_user`
    FOREIGN KEY (`cod_user`)
    REFERENCES `conjuntos_reservas`.`USERS` (`cod_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cod_place`
    FOREIGN KEY (`cod_place`)
    REFERENCES `conjuntos_reservas`.`PLACES` (`cod_place`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conjuntos_reservas`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conjuntos_reservas`.`booking` (
  `booking_date` DATE NOT NULL,
  `cod_booking` INT(11) NOT NULL,
  `cod_user` INT(11) NOT NULL,
  PRIMARY KEY (`cod_booking`, `booking_date`),
  CONSTRAINT `FK_booking`
    FOREIGN KEY (`cod_booking`)
    REFERENCES `conjuntos_reservas`.`house` (`cod_house`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `conjuntos_reservas`.`places`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conjuntos_reservas`.`places` (
  `cod_place` INT(11) NOT NULL,
  `cod_category` INT(11) NOT NULL,
  `place_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_place`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `conjuntos_reservas`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conjuntos_reservas`.`roles` (
  `cod_rol` INT(11) NOT NULL,
  `rol_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cod_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `conjuntos_reservas`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conjuntos_reservas`.`users` (
  `cod_rol` INT(11) NOT NULL,
  `cod_user` INT(11) NOT NULL,
  `cod_house` INT(11) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `user_lastname` VARCHAR(45) NOT NULL,
  `user_birthday` DATE NOT NULL,
  `user_id` INT(11) NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  `user_pass` VARCHAR(45) NOT NULL,
  `user_phone` VARCHAR(80) NOT NULL,
  `user_state` TINYINT(4) NOT NULL,
  PRIMARY KEY (`cod_user`),
  INDEX `ind_user_house` (`cod_house` ASC) VISIBLE,
  INDEX `FK_user_rol` (`cod_rol` ASC) VISIBLE,
  CONSTRAINT `FK_user_rol`
    FOREIGN KEY (`cod_rol`)
    REFERENCES `conjuntos_reservas`.`roles` (`cod_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_house`
    FOREIGN KEY (`cod_house`)
    REFERENCES `conjuntos_reservas`.`house` (`cod_house`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
